travelblog/urls.py
from django.contrib import admin
from django.urls import path,re_path
from django.conf.urls import url,include
from django.views.static import serve
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('web.urls',)),
    path('ckeditor/',include('ckeditor_uploader.urls')),

    re_path('media/(?P<path>.*)$', serve, { 'document_root': settings.MEDIA_ROOT}),
    re_path('static/(?P<path>.*)$', serve, { 'document_root': settings.STATIC_FILE_ROOT}),
]

web/urls.py
from django.urls import path
from . import views




urlpatterns = [
    path('',views.about, name="home"),
    path('blog/',views.index,name="index"),
    path('hotels/',views.hotels,name="hotels"),
    path('hotel_booking/<str:pk>/',views.booking, name="booking"),
    path('detail/<str:pk>/',views.blogdetails, name="blogdetail"),
    path('profile/<str:user>/',views.profile,name="profile"),
  

    path('cretepost/',views.createpost,name='createpost'),
    path('updatepost/<str:pk_update>/',views.updatepost,name="updatepost"),
    path('delete/<str:pk_del>/',views.deletepost,name="deletepost"),

    path('editprofile/',views.editprofile,name = "editprofile"),
    path('editimg/',views.editimg,name="editimg"),

    path('login/',views.loginpage,name="login"),
    path('registration/',views.registrationpage,name="registration"),
    path('logout/',views.logoutpage,name='logout')
]

web/models.py
from django.db import models
from django.contrib.auth.models import User
from versatileimagefield.fields import VersatileImageField
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField


# Create your models here.


class ProfileImg(models.Model):
    user = models.OneToOneField(User,null=True, on_delete=models.CASCADE)
    profileimg = VersatileImageField(upload_to='profile',default='prifiledummy.png')


    def __str__(self):
        return self.user.username


class Blog(models.Model):
    title = models.CharField(max_length=250,null=True)
    description = models.CharField(max_length=1000,null=True)
    detailDiscription = RichTextUploadingField(blank=True,null=True)
    place =  models.CharField(max_length=300,null=True)
    date = models.DateTimeField(auto_now_add=True,null=True)
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    cover_image = VersatileImageField(upload_to='web',default='default.jpg')
    twoimage = VersatileImageField(upload_to='web',default='default.jpg')
    threeimage = VersatileImageField(upload_to='web',default='default.jpg')

    def __str__(self):
        return self.title

class Hotel(models.Model):
    name=models.CharField(max_length=200)
    place=models.CharField(max_length=200)
    image=models.ImageField(null=True, blank=True)
    description=models.TextField(max_length=1000)
    roomtype=models.CharField(max_length=200)
    count=models.IntegerField(null=True)
    rate=models.FloatField(max_length=200)
    available_rooms=models.IntegerField(null=True)

    def __str__(self):
        return self.name


class Booking(models.Model):
    room_count=models.IntegerField(null=True)
    rate=models.FloatField(max_length=200, null=True, blank=True)
    hotel=models.ForeignKey(Hotel,on_delete=models.CASCADE)
    check_in=models.DateField(null=True)
    check_out=models.DateField(null=True)
    name=models.CharField(max_length=200)
    phone=models.IntegerField(null=True)

    

web/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Blog, User, Hotel
from django.contrib.auth.forms import UserCreationForm
from .form import UserRegisterForm, PostBlog, UserProfile, Useredit, Booking
from django.contrib import messages
from django.contrib.auth import authenticate,   login, logout 
from django.contrib.auth.decorators import login_required
from .filters import ProfileFilter,PostFilter
from django.db.models import Q

def index(request):
   posts = Blog.objects.order_by('-id')
   authors = User.objects.all()
   myfilter = PostFilter(request.GET,queryset=posts)
   posts = myfilter.qs
   # user = posts.user_set.all()
   context = {
      'posts':posts,
      'myfilter':myfilter,
      'authors':authors
      # 'user':user
   }
   return render(request,'index.html',context)

def hotels(request):
   hotels = Hotel.objects.all()
   q = request.GET.get('search')
   if q is not None:
      hotels = Hotel.objects.filter(Q(name__icontains=q) | Q(place__icontains=q))
   context = {
      'hotels':hotels
   }
   return render(request,'hotels.html',context)

def booking(request,pk):
   hotel = Hotel.objects.get(pk=pk)
   form = Booking()
   if request.method == 'POST':
      form = Booking(request.POST,request.FILES)
      form.instance.user = request.user
      form.instance.hotel = hotel
      if form.is_valid():
         form.save()
         messages.success(request, 'Booking completed')
         return redirect('hotels')
   context = {
      'hotel':hotel,
      'form':form
   }
   return render(request,'hotel_booking.html',context) 

def blogdetails(request,pk):
   posts = Blog.objects.get(id=pk)
   context = {
      'posts':posts
   }
   return render(request,'blog_detail.html',context)


def about(request):
   return render(request,'home.html')




def loginpage(request):
   if request.user.is_authenticated:
      return redirect('index')
   else:
      if request.method == 'POST':
         username = request.POST.get('username')
         password = request.POST.get('password')
         user = authenticate(request,username=username,password=password)
         if user is not None:
            login(request,user)
            return redirect('index')

      return render(request,'login.html')




def registrationpage(request):
   if request.user.is_authenticated:
      return redirect('index')
   else:
      form = UserRegisterForm()
      if request.method == 'POST':
         form = UserRegisterForm(request.POST)
         if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request,'user created for '+ user)
            return redirect('login')

      context = {
         'form' : form
      }
      return render(request,'registration.html',context)



def logoutpage(request):
   logout(request)
   return redirect('login')

   
@login_required(login_url='login')
def profile(request,user):
   user = User.objects.get(id=user)
   posts = user.blog_set.all()
   total_posts = posts.count()
   myfilters = ProfileFilter(request.GET,queryset = posts)
   posts = myfilters.qs
   context = {
      'user':user,
      'posts':posts,
      'total_posts': total_posts,
      'myfilters':myfilters
   }
   return render(request,'profile.html',context)

@login_required(login_url='login')
def editprofile(request):
   form = Useredit(instance=request.user)
   if request.method == 'POST':
      form = Useredit(request.POST,instance=request.user)
      user_id = request.user.id
      if form.is_valid():
         form.save()
         return redirect('/profile/{}/'.format(user_id))
   context = {
      'form':form,
      
   }
   return render(request,'editprofile.html',context)


@login_required(login_url='login')
def editimg(request):
   form = UserProfile(instance=request.user.profileimg)
   if request.method == 'POST':
      form = UserProfile(request.POST,request.FILES,instance=request.user.profileimg)
      form.instance.user = request.user
      user_id = request.user.id
      if form.is_valid():
         form.save()
         return redirect('/profile/{}/'.format(user_id))
   context = {
      'form':form
   }
   return render(request,'editimg.html',context)

@login_required(login_url='login')
def createpost(request):
   form = PostBlog()
   if request.method == 'POST':
      form = PostBlog(request.POST,request.FILES)
      form.instance.user = request.user
      if form.is_valid():
         form.save()
         return redirect('index')

   context = {
      'form':form
   }
   return render(request,'createpost.html',context)




def updatepost(request,pk_update):
   post = Blog.objects.get(id=pk_update)
   form = PostBlog(instance=post)
   user_id = request.user.id
   if request.method == 'POST':
      form = PostBlog(request.POST,request.FILES,instance=post)
      if form.is_valid():
         form.save()
         return redirect('/profile/{}/'.format(user_id))
   context = {
      'form':form
   }
   return render(request,'createpost.html',context)


def deletepost(request,pk_del):
   post = Blog.objects.get(id=pk_del)
   user_id = request.user.id
   if request.method == 'POST':
      post.delete()
      return redirect('/profile/{}/'.format(user_id))
   context = {
      'item':post,
      'userid':user_id
   }
   return render(request,'delete.html',context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
 
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- CSS only -->
    <link rel="stylesheet" href="{% static '/css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
</head>
<body>
    
    {% include 'nav.html' %}
    {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
    {% block content %}

    {% endblock%}
<!-- JavaScript Bundle with Popper -->
{% comment %} <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> {% endcomment %}
<script src="https://code.jquery.com/jquery-3.6.0.js"></script>
<script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script></body>
<script src="https://unpkg.com/aos@next/dist/aos.js"></script>
<script>
  AOS.init();
</script>
<script>
$(document).ready(function () {
  console.log("date");
  $(function () {
    $(".dateinput").datepicker();
  });
})
 </script>
</html>

templates/blog_detail.html
{% extends 'base.html' %}
{% load static%}
{% block content %}
    <div class="container px-0 rounded-3">

        <div class="detail_view bg-white mt-5 p-3">        
            <h1 >{{posts.title}}</h1>  
            <p class="mt-3">{{posts.date}}</p>   
            <div class="author mt-3">
                <h6 class="mr-3"> Author : {{posts.user}} 
                    <span>
                        {% if posts.user.profileimg %}
                        <img src="{{posts.user.profileimg.profileimg.url}}" alt="">
                        {% else %}
                        <img src="{% static 'images/prifiledummy.png' %}" alt="">
                        {% endif %}
                    </span>
                </h6>
            </div>   
            <p class="text-dark mt-5">
                {{posts.description}}
            </p>
            <div class="richtext_uploads mt-5">
                {{posts.detailDiscription|safe}}
            </div>
        </div>

    </div>
{% endblock %}

templates/createpost.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">

    <div class="postblog-user">
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            {{form.media}}
            <input class="submit btn btn-lg bg-primary text-white" type="submit" value="submit">
        </form>
    </div>

</div>
    
{% endblock %}

templates/delete.html
{% extends 'base.html' %}
{% block content %}
    <div class="container deletepage">
        <p>are you sure you want to delete post <span>{{item}}</span></p>
        <form action="" method="POST">
            {% csrf_token %}
            <div>

                <input class="btn btn-md bg-danger text-white" type="submit" value="submit">
                <a class="btn btn-md bg-warning text-white" href="{% url 'profile' userid %}">cancel</a>
    
            </div>
          
        </form>

    </div>

{% endblock %}

templates/editimg.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <div>
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{form}}
                <input type="submit" value="submit">
            </form>
        </div>
    </div>
{% endblock %}

templates/editprofile.html
{% extends 'base.html' %}

{% block content  %}

<div class="container">
    <h1>editprifile</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="submit">
    </form>
    
</div>

{% endblock%}

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content%}
  
    <div class="front_section">
        <div class="container my-5">         
            <div class="row justify-content-between">
                <div class="col-lg-6 col-sm-12 imgcontainer" data-aos="fade-right"  data-aos-duration="1800">
                    <img class="w-100" src="{% static 'images/blogvector.png' %}" alt="">
                </div>
                <div class="col-lg-4 col-md-12 textcontainer" data-aos="fade-left" data-aos-duration="1800">
                    <h2>
                        Lorem ipsum, dolor sit amet <br>
                        set bintu
                    </h2>
                   
                    <a href="" class="btn btn-md w-50 text-white">post a blog </a>
                    
                </div>
            </div>
        </div>
    </div>
    <div class="container about_section py-5">
        <div class="text-center">
            <h1 class="text-capitalize mb-5">about us</h1>
            <div class="col-8 bg-white mb-5 p-5" style="box-shadow: 0 2px 3px -2px rgb(0 0 0 / 50%);" data-aos="fade-down"
            data-aos-easing="linear"
            data-aos-duration="1000">
                <h5>Lorem ipsum dolor </h5>
                <p class="mt-4">Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum nihil rem eos facilis suscipit ea quae! Asperiores fugit porro fugiat quasi est explicabo molestias, vel eum magni qui voluptatum consequuntur?</p>
            </div>
        </div>

    </div>
    <div class="contact_section  py-5" >
        <div class="container my-5"> 
            <h1 class="text-center text-capitalize">contact us </h1>
            <div class="row justify-content-between mt-5">
                <div class="col-lg-5 col-sm-12 formcontainer" data-aos="fade-up" data-aos-offset="100" data-aos-duration="1000">
                    <form action="" method="">
                        <input class="mt-3 py-2 px-3" type="text" placeholder="Name">
                        <br>
                        <input class="mt-3 py-2 px-3" type="text" placeholder="Email">
                        <br>
                        <textarea class="mt-3 py-2 px-3" name=""  placeholder="message"></textarea>
                        <br>
                        <div class="text-end">
                            <input class="mt-3 btn btn-md bg-primary text-white" type="submit" value="submit">
                        </div>
                    </form>
                </div>
                <div class="col-lg-5 col-sm-12" data-aos="fade-down" data-aos-offset="100" data-aos-duration="1000">
                    <img class="w-100" src="{% static 'images/emailvector.png' %}" alt="">
                </div>
            </div>
        </div>
    </div>
    <div class="footer py-4">
        <div class="row justify-content-between text-center">
            <p class="col-lg-5 col-sm-12 mb-0">2021 © comapany name. All rights reserved.</p>
            <p class="col-lg-5 col-sm-12 mb-0">developed by name</p>
        </div>
    </div>


{% endblock %}

templates/hotel_booking.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">

    <div class="postblog-user">
                <div class="col-lg-9 col-md-7">
                <div class="blog-posts col-lg-12 row bg-white mt-5">
                    <div class="col-lg-4 col-md-5 col-sm-12 px0"><img class="w-100" src="{{hotel.image.url}}" alt=""></div>
                    <div class="col-lg-8 col-md-7 col-sm-12 py-4 px-4">
                      <div class="row"> 
                       <a class="col-8" href="#">
                        <h2 >{{hotel.name}}</h2>
                       </a>
                      </div>
                      <p class="text-capitalize">destination: {{hotel.place}}</p>
                        <p>About - {{hotel.description}}</p>
    
                        
                        <p class="col-4 date text-capitalize">Total rooms -  {{hotel.count}}</p>
                        <p class="col-4 date text-capitalize">Perday rate - {{hotel.rate}}</p>
                    </div>
                </div>
                
            </div>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            {{form.media}}
            <input class="submit btn btn-lg bg-primary text-white" type="submit" value="submit">
        </form>
    </div>

</div>
    
{% endblock %}

templates/hotels.html
{% extends 'base.html' %}
{% load static %}
{% block content  %}
    <div class="container homepage">
        <div class="row">
            <div class="col-lg-12 mt-1 mobile_search ">
                <div class="bg-white">
                    
                    <form action="" method="GET">
                        <input class="mt-1 col-12 filteritem" type="text" name="search" placeholder="search by tiltle or place">
                        <input class="mt-1 col-12 btn btn-sm bg-info text-white" type="submit" value="submit">
                    </form>
                    
                </div>
            </div>
            
            <div class="col-lg-9 col-md-7">
                {% for hotel in hotels%}
                <div class="blog-posts col-lg-12 row bg-white mt-5">
                    <div class="col-lg-4 col-md-5 col-sm-12 px0"><img class="w-100" src="{{hotel.image.url}}" alt=""></div>
                    <div class="col-lg-8 col-md-7 col-sm-12 py-4 px-4">
                      <div class="row"> 
                       <a class="col-8" href="#">
                        <h2 >{{hotel.name}}</h2>
                       </a>
                      </div>
                      <p class="text-capitalize">destination: {{hotel.place}}</p>
                        <p>About - {{hotel.description}}</p>
    
                        
                        <p class="col-4 date text-capitalize">Total rooms -  {{hotel.count}}</p>
                        <p class="col-4 date text-capitalize">Perday rate - {{hotel.rate}}</p>
                        <a class="btn btn-primary" href="{% url 'booking' hotel.pk%}"> Book now</a>
                    </div>
                </div>
                {% empty %}
                    <p>No data found !</p>
                {% endfor%}
                
            </div>
            <div class="col-lg-3 col-md-3 mt-5 right_menu ">
                <div class="bg-white p-1">
                    <form action="" method="GET">
                        <input class="mt-1 filteritem" type="text" name="search" placeholder="search by tiltle or place">
                        <input class="mt-2 ml-5 btn btn-sm text-white bg-info" type="submit" value="search">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content  %}
    <div class="container homepage">
        <div class="row">
            <div class="col-lg-12 mt-1 mobile_search ">
                <div class="bg-white">
                    
                    <form action="" method="GET">
                        <input class="mt-1 col-12 filteritem" type="text" name="checkDate" placeholder="search by date">
                        <input class="mt-1 col-12 filteritem" type="text" name="search" placeholder="search by tiltle or place">
                        <input class="mt-1 col-12 btn btn-sm bg-info text-white" type="submit" value="submit">
                    </form>
                    
                </div>
            </div>
            <div class="col-lg-9 col-md-7">
                {% for post in posts%}
                <div class="blog-posts col-lg-12 row bg-white mt-5">
                    <div class="col-lg-4 col-md-5 col-sm-12 px0"><img class="w-100" src="{{post.cover_image.url}}" alt=""></div>
                    <div class="col-lg-8 col-md-7 col-sm-12 py-4 px-4">
                      <div class="row"> 
                       <a class="col-8" href="{% url 'blogdetail' post.id %}">
                        <h2 >{{post.title}}</h2>
                       </a>
                        <p class="col-4 date text-capitalize text-center"> {{post.date |date:"M d Y"}}</p>
                      </div>
                      <p class="text-capitalize">destination: {{post.place}}</p>
                        <p>{{post.description}}</p>
    
                        <div class="author mt-3  text-end">
                            <h6 class="mr-3"> Author: {{post.user}} 
                                <span>
                                    {% if post.user.profileimg %}
                                    <img src="{{post.user.profileimg.profileimg.url}}" alt="">
                                    {% else %}
                                    <img src="{% static 'images/prifiledummy.png' %}" alt="">
                                    {% endif %}
                                </span>
                            </h6>
                        </div>
                    </div>
                </div>
                {% empty %}
                    <p>No data found !</p>
                {% endfor%}
                
            </div>
            <div class="col-lg-3 col-md-3 mt-5 right_menu ">
                <div class="bg-white p-1">
                    <form action="" method="GET">
                        <input class="mt-1 filteritem" type="text" name="checkDate" placeholder="search by date">
                        <input class="mt-1 filteritem" type="text" name="search" placeholder="search by tiltle or place">
                        <input class="mt-2 ml-5 btn btn-sm text-white bg-info" type="submit" value="search">
                    </form>
                    <div class="latest my-4">
                        <div>
                            <h6 class="text-center text-capitalize mb-3">lorem ipsem </h6>
                            {% for author in authors|slice:"5"%}
                            {% if author.blog_set.count >= 2 %}
                            <table>
                                <tr>
                                    <td class="col-3  text-center"><img src="{{author.profileimg.profileimg.url}}" alt=""> </td>
                                    <td class="col-7">{{author}}</td>
                                    <td class="col-2">{{author.blog_set.count }}</td>
                                </tr>
                            </table>
                            {% endif %}
                            {% endfor %}
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block content %}

<div class="container loginpage">

    {% for message in messages %}
        <p>{{message}}</p>
    {% endfor %}

    <h1>user login</h1>

    <form action="" method="POST">
        {% csrf_token%}

        <input type="text" name="username" placeholder="Username..." class="form-control">
        <input  type="password" name="password" placeholder="Password..." class="form-control mt-3" >

        <input class="btn btn-lg bg-primary text-white mt-3 login_btn" type="submit" value="Login">


    </form>
    <p class="mt-4">
        no accout !<a href="{% url 'registration' %}">register</a>
    </p>
</div>

{% endblock %}

templates/nav.html
{% load static %}

<div class="container mainnavbar mt-4 px-0">
  
  <nav class="navbar navbar-expand-lg navbar-light bg-white">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      {% if user.is_authenticated%} 
      <button class="profilepic_button" >
        <a class="profilepic" href="" >  
          {% if user.profileimg %}
          <div>
              <img src="{{user.profileimg.profileimg.url}}" alt="">
          </div>
          {% else %}
          <div>
              <img src="{% static 'images/prifiledummy.png' %}" alt="">
          </div>
          {% endif %} 
        </a>
      </button>
      {% endif %}
      <button class="navbar-toggler"  type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">       
        <i class="fas fa-bars"></i>
      </button>
      
      <div class="collapse navbar-collapse justify-content-end " id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto ">
          <li class="nav-item active">
            <a class="nav-link " href="{% url 'home' %}">Home</a>
          </li>
          <li class="nav-item mr-5">
            <a class="nav-link" href="{% url 'index' %}">Blog</a>
          </li>
          <li class="nav-item mr-5">
            <a class="nav-link" href="{% url 'hotels' %}">Hotels</a>
          </li>
          {% if user.is_authenticated%} 
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              {{user.username}}
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="{% url 'logout' %}">logout</a></li>
              <li><a class="dropdown-item" href="{% url 'profile' user.id %}">Profile</a></li>
            </ul>
          </li>
          <a class="profilepic " href="" >  
            {% if user.profileimg %}
            <div>
                <img src="{{user.profileimg.profileimg.url}}" alt="">
            </div>
            {% else %}
            <div>
                <img src="{% static 'images/prifiledummy.png' %}" alt="">
            </div>
            {% endif %} 
          </a>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">login</a>
          </li>
          {% endif%}
          <li class="post_blog">
            <a class="btn btn-md  text-white text-capitalize  w-100" href="{% url 'createpost'%}">post a blog</a>
          </li>
         
        </ul>
       
      </div>
    </div>
  </nav>
    
</div>

templates/profile.html
{% extends 'base.html' %}
{% load static %}
{%  block content %}

<div class="container profile_page px-0 py-3">
   

    <div class="row justify-content-between mx-1 mt-4">
        <div class="col-lg-5 col-sm-12 bg-white px-5 py-2 mt-3 row userinfo-main" style="background: #fff; box-shadow: 0 2px 3px -2px rgb(0 0 0 / 50%);" >
           <div class="col-lg-6 col-xs-12 mt-3 user-info">
                <h5>User Name : <span>{{user.username}}</span></h5>
                <p>User Email : <span>{{user.email}}</span></p>
                <a href="{% url 'editprofile' %}" class="btn btn-md  text-white my-2">Edit User <i class="fas fa-user-edit pl-3"></i></a>
           </div>
           <div class="col-lg-6 col-xs-12 total-posts text-center mt-3">
               <h4>Total Posts</h4>
               <p>{{total_posts}}</p>
           </div>
        </div>
        <div class="col-lg-3 col-sm-12 mt-3 profileimgs  text-center py-2" >
            {% if user.profileimg %}
            <div class="img-container bg-white" style="box-shadow: 0 2px 3px -2px rgb(0 0 0 / 50%);">
                <img src="{{user.profileimg.profileimg.url}}" alt="">
                <button class="edittag"><a href="{% url 'editimg' %}">edit profile<i class="fas fa-portrait"></i></a></button>
            </div>
            {% else %}
            <div class="img-container bg-white">
                <img src="{% static 'images/prifiledummy.png' %}" alt="">
                 <span class="edittag"><a href="{% url 'editimg' %}">edit profile<i class="fas fa-portrait"></i></a></span>
            </div >
            {% endif %}
           
        </div>

    </div>

    

    <div class="card card-body mt-5" style="background: #fff; box-shadow: 0 2px 3px -2px rgb(0 0 0 / 50%);" >
        
        <a class="btn btn-primary  btn-sm btn-block" href="{% url 'createpost' %}">Post a blog</a>

        <h5 class="text-capitalize mt-4">your blogs</h5>
        <div class="filters">
            <form action="" method="GET">    
                <input class="filter_items" type="text" placeholder="Search by title" name="place" id="id_place">
                <input class="filter_items" type="text" name="check_date" placeholder="Search by date" id="id_check_date">
                <input class="btn btn-sm bg-info text-white" type="submit" value="Search">
            </form>
        </div>
        <table class="table table-hover">
            <tr>
                <th class="col-lg-6 col-12">Title</th>
                <th class="col-lg-4 col-12 text-center">Date</th>
                <th class="col-lg-1 col-12">update</th>
                <th class="col-lg-1 col-12">delete</th>
            </tr>
            
            {% for post in posts %}
            
            
            <tr>
                <th class="col-lg-6 col-12">{{post.title}}</th>
                <th class="col-lg-4 col-12 text-center">{{post.date}}</th>
                <th class="col-lg-1 col-12">
                    <a class="btn btn-primary btn-sm" href="{% url 'updatepost' post.id %}">UPDATE</a>
                </th>
                <th class="col-lg-1 col-12">
                    <a class="btn btn-danger btn-sm" href="{% url 'deletepost' post.id %}">DELETE</a>
                </th>
            </tr>

            {% endfor %}
        </table>
    </div>
</div>

{% endblock %}